name: Class-ReturnValue
version: 0.52
abstract: A smart return value object
author: Jesse Vincent <jesse@bestpractical.com>
license: perl
distribution_type: module
requires:
  Test::More: 0
  Test::Inline: 0
  Devel::StackTrace: 0
private:
  directory:
    - inc
generated_by: Module::Install version 0.24
